# Generated by Django 4.1.5 on 2023-06-03 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_estate_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='estate_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='market.estatetype', verbose_name='estate type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estate',
            name='room_count',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='market.roomcount', verbose_name='room count'),
            preserve_default=False,
        ),
    ]
